# Generated by Django 4.2.13 on 2024-06-14 01:02

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
