# Generated by Django 4.2.13 on 2024-06-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_account_otp_secret_account_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_authenticate',
            field=models.BooleanField(default=False),
        ),
    ]
