# Generated by Django 4.2.13 on 2024-06-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_account_is_authenticate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductVideo',
        ),
    ]
