# Generated by Django 5.0.4 on 2024-05-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description_product_name_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoinalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photoinalbum',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photoinalbum',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='price', upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoInAlbum',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
